export const SET_COUNTRIES = "SET_COUNTRIES";
export const FETCH_COUNTRIES_FAILED = "FETCH_COUNTRIES_FAILED";
export const SELECT_CONTINENT = "SELECT_CONTINENT";
export const SELECT_REGION = "SELECT_REGION";
export const SET_COUNTRY_INFO = "SET_COUNTRY_INFO";
export const UNSET_COUNTRY_INFO = "UNSET_COUNTRY_INFO";
export const SET_COUNTRY_STATISTICS = "SET_COUNTRY_STATISTICS";
export const UNSET_COUNTRY_STATISTICS = "UNSET_COUNTRY_STATISTICS";
