export const countryStatsMock = {
  info: {
    id: 110,
    name: 'Kazakhstan',
    region: 'Southern and Central Asia',
    continent: 'Asia',
    alpha2code: 'KZ',
    alpha3code: 'KAZ',
    surfaceArea: 2724900,
    population: 16223000,
    lifeExpectancy: 63,
    independenceYear: 1991,
    governmentForm: 'Republic',
    localName: 'Qazaqstan',
    independent: true,
    fullyRecognized: true,
    visited: true,
    statistics: true,
    flagUrl: 'https://flagcdn.com/kz.svg',
    borders: '["CHN","KGZ","RUS","TKM","UZB"]',
  },
  citiesVisited: [
    'Almaty',
    'Astana',
    'Big Almaty Lake',
    'Charyn Canyon',
    'Kaindy Lake',
    'Kolsay lake',
    'Korday',
    'Medeu',
    'Otrar',
    'Sairam',
    'Sauran',
    'Shymkent',
    'Tamgaly Tas',
    'Taraz',
    'Turgen',
    'Turkistan',
  ],
  statesVisited: [
    {
      name: 'Almaty',
      code: 'KZ-ALM',
    },
    {
      name: 'Nur-Sultan',
      code: 'KZ-AST',
    },
    {
      name: 'Zhambyl',
      code: 'KZ-ZHA',
    },
    {
      name: 'Türkistan',
      code: 'KZ-YUZ',
    },
    {
      name: 'Shymkent',
      code: 'KZ-SHY',
    },
  ],
  kilometersWalked: 230.04,
  nights: {
    count: {
      free: '30',
      paid: '0',
      total: 30,
    },
    spots: {
      Wildcamping: 16,
      Review: 10,
      Airport: 2,
      Hospitality: 2,
    },
    infoExtra: {
      Tenda: 1,
    },
  },
  hitchhikes: {
    totalKilometers: 4226,
    totalKilometersOpenAir: null,
    daysOnTheRoad: 19,
    totalCars: 52,
    distances: {
      longest: '1105.00',
      shortest: '0.00',
      average: '79.735849',
    },
    minutesWaiting: {
      total: 555.5,
      waits: {
        longest: '96.00',
        shortest: '0.00',
        average: '10.481132',
      },
    },
    statsPerHour: [
      {
        hour: '7',
        rides: 1,
        distance: '27.00',
        minutes: '29.00',
      },
      {
        hour: '8',
        rides: 1,
        distance: '21.00',
        minutes: '8.00',
      },
      {
        hour: '9',
        rides: 6,
        distance: '322.00',
        minutes: '15.00',
      },
      {
        hour: '10',
        rides: 6,
        distance: '1552.00',
        minutes: '52.00',
      },
      {
        hour: '11',
        rides: 6,
        distance: '291.00',
        minutes: '73.00',
      },
      {
        hour: '12',
        rides: 2,
        distance: '304.00',
        minutes: '22.00',
      },
      {
        hour: '13',
        rides: 10,
        distance: '379.00',
        minutes: '24.00',
      },
      {
        hour: '14',
        rides: 6,
        distance: '334.00',
        minutes: '33.50',
      },
      {
        hour: '15',
        rides: 2,
        distance: '303.00',
        minutes: '96.00',
      },
      {
        hour: '16',
        rides: 4,
        distance: '327.00',
        minutes: '46.00',
      },
      {
        hour: '17',
        rides: 3,
        distance: '203.00',
        minutes: '44.00',
      },
      {
        hour: '18',
        rides: 2,
        distance: '60.00',
        minutes: '17.00',
      },
      {
        hour: '19',
        rides: 2,
        distance: '40.00',
        minutes: '71.00',
      },
      {
        hour: '20',
        rides: 2,
        distance: '63.00',
        minutes: '25.00',
      },
    ],
  },
  expenses: {
    sum: 874.62,
    categories: {
      DRINK: '200',
      FOOD: '83.1',
      'INTERNATIONAL TRANSPORT': '455.22',
      OTHERS: '100.28',
      SIGHTSEEING: '60.47',
      TRANSPORT: '25.58',
    },
  },
};
