export const visitedCountriesMock = [
  {
    name: 'Albania',
    continent: 'Europe',
    region: 'Southern Europe',
    alpha3code: 'ALB',
    numberOfSpots: 6,
  },
  {
    name: 'Algeria',
    continent: 'Africa',
    region: 'Northern Africa',
    alpha3code: 'DZA',
    numberOfSpots: 11,
  },
  {
    name: 'Andorra',
    continent: 'Europe',
    region: 'Southern Europe',
    alpha3code: 'AND',
    numberOfSpots: 7,
  },
  {
    name: 'Armenia',
    continent: 'Asia',
    region: 'Transcaucasia',
    alpha3code: 'ARM',
    numberOfSpots: 11,
  },
  {
    name: 'Austria',
    continent: 'Europe',
    region: 'Western Europe',
    alpha3code: 'AUT',
    numberOfSpots: 2,
  },
  {
    name: 'Belgium',
    continent: 'Europe',
    region: 'Western Europe',
    alpha3code: 'BEL',
    numberOfSpots: 4,
  },
  {
    name: 'Bosnia and Herzegovina',
    continent: 'Europe',
    region: 'Southern Europe',
    alpha3code: 'BIH',
    numberOfSpots: 3,
  },
  {
    name: 'Bulgaria',
    continent: 'Europe',
    region: 'Eastern Europe',
    alpha3code: 'BGR',
    numberOfSpots: 7,
  },
  {
    name: 'Cambodia',
    continent: 'Asia',
    region: 'Southeast Asia',
    alpha3code: 'KHM',
    numberOfSpots: 7,
  },
  {
    name: 'Croatia',
    continent: 'Europe',
    region: 'Southern Europe',
    alpha3code: 'HRV',
    numberOfSpots: 3,
  },
  {
    name: 'Cuba',
    continent: 'North America',
    region: 'Caribbean',
    alpha3code: 'CUB',
    numberOfSpots: 7,
  },
  {
    name: 'Czech Republic',
    continent: 'Europe',
    region: 'Eastern Europe',
    alpha3code: 'CZE',
    numberOfSpots: 2,
  },
  {
    name: 'France',
    continent: 'Europe',
    region: 'Western Europe',
    alpha3code: 'FRA',
    numberOfSpots: 30,
  },
  {
    name: 'Gambia',
    continent: 'Africa',
    region: 'Western Africa',
    alpha3code: 'GMB',
    numberOfSpots: 8,
  },
  {
    name: 'Georgia',
    continent: 'Asia',
    region: 'Transcaucasia',
    alpha3code: 'GEO',
    numberOfSpots: 7,
  },
  {
    name: 'Germany',
    continent: 'Europe',
    region: 'Western Europe',
    alpha3code: 'DEU',
    numberOfSpots: 6,
  },
  {
    name: 'Greece',
    continent: 'Europe',
    region: 'Southern Europe',
    alpha3code: 'GRC',
    numberOfSpots: 4,
  },
  {
    name: 'Hungary',
    continent: 'Europe',
    region: 'Eastern Europe',
    alpha3code: 'HUN',
    numberOfSpots: 4,
  },
  {
    name: 'India',
    continent: 'Asia',
    region: 'Southern and Central Asia',
    alpha3code: 'IND',
    numberOfSpots: 28,
  },
  {
    name: 'Indonesia',
    continent: 'Asia',
    region: 'Southeast Asia',
    alpha3code: 'IDN',
    numberOfSpots: 25,
  },
  {
    name: 'Iran',
    continent: 'Asia',
    region: 'Southern and Central Asia',
    alpha3code: 'IRN',
    numberOfSpots: 15,
  },
  {
    name: 'Israel',
    continent: 'Asia',
    region: 'Middle East',
    alpha3code: 'ISR',
    numberOfSpots: 4,
  },
  {
    name: 'Italy',
    continent: 'Europe',
    region: 'Southern Europe',
    alpha3code: 'ITA',
    numberOfSpots: 28,
  },
  {
    name: 'Jordan',
    continent: 'Asia',
    region: 'Middle East',
    alpha3code: 'JOR',
    numberOfSpots: 7,
  },
  {
    name: 'Kazakhstan',
    continent: 'Asia',
    region: 'Southern and Central Asia',
    alpha3code: 'KAZ',
    numberOfSpots: 16,
  },
  {
    name: 'Kyrgyzstan',
    continent: 'Asia',
    region: 'Southern and Central Asia',
    alpha3code: 'KGZ',
    numberOfSpots: 13,
  },
  {
    name: 'Laos',
    continent: 'Asia',
    region: 'Southeast Asia',
    alpha3code: 'LAO',
    numberOfSpots: 7,
  },
  {
    name: 'Latvia',
    continent: 'Europe',
    region: 'Baltic Countries',
    alpha3code: 'LVA',
    numberOfSpots: 1,
  },
  {
    name: 'Lebanon',
    continent: 'Asia',
    region: 'Middle East',
    alpha3code: 'LBN',
    numberOfSpots: 8,
  },
  {
    name: 'Luxembourg',
    continent: 'Europe',
    region: 'Western Europe',
    alpha3code: 'LUX',
    numberOfSpots: 1,
  },
  {
    name: 'Macedonia',
    continent: 'Europe',
    region: 'Southern Europe',
    alpha3code: 'MKD',
    numberOfSpots: 7,
  },
  {
    name: 'Malaysia',
    continent: 'Asia',
    region: 'Southeast Asia',
    alpha3code: 'MYS',
    numberOfSpots: 5,
  },
  {
    name: 'Malta',
    continent: 'Europe',
    region: 'Southern Europe',
    alpha3code: 'MLT',
    numberOfSpots: 4,
  },
  {
    name: 'Moldova',
    continent: 'Europe',
    region: 'Eastern Europe',
    alpha3code: 'MDA',
    numberOfSpots: 2,
  },
  {
    name: 'Monaco',
    continent: 'Europe',
    region: 'Western Europe',
    alpha3code: 'MCO',
    numberOfSpots: 2,
  },
  {
    name: 'Montenegro',
    continent: 'Europe',
    region: 'Southern Europe',
    alpha3code: 'MNE',
    numberOfSpots: 5,
  },
  {
    name: 'Morocco',
    continent: 'Africa',
    region: 'Northern Africa',
    alpha3code: 'MAR',
    numberOfSpots: 14,
  },
  {
    name: 'Myanmar',
    continent: 'Asia',
    region: 'Southeast Asia',
    alpha3code: 'MMR',
    numberOfSpots: 9,
  },
  {
    name: 'Nagorno-Karabakh',
    continent: 'Asia',
    region: 'Transcaucasia',
    alpha3code: 'NKB',
    numberOfSpots: 7,
  },
  {
    name: 'Netherlands',
    continent: 'Europe',
    region: 'Western Europe',
    alpha3code: 'NLD',
    numberOfSpots: 3,
  },
  {
    name: 'Oman',
    continent: 'Asia',
    region: 'Middle East',
    alpha3code: 'OMN',
    numberOfSpots: 23,
  },
  {
    name: 'Palestine',
    continent: 'Asia',
    region: 'Middle East',
    alpha3code: 'PSE',
    numberOfSpots: 5,
  },
  {
    name: 'Poland',
    continent: 'Europe',
    region: 'Eastern Europe',
    alpha3code: 'POL',
    numberOfSpots: 2,
  },
  {
    name: 'Portugal',
    continent: 'Europe',
    region: 'Southern Europe',
    alpha3code: 'PRT',
    numberOfSpots: 22,
  },
  {
    name: 'Romania',
    continent: 'Europe',
    region: 'Eastern Europe',
    alpha3code: 'ROU',
    numberOfSpots: 36,
  },
  {
    name: 'San Marino',
    continent: 'Europe',
    region: 'Southern Europe',
    alpha3code: 'SMR',
    numberOfSpots: 1,
  },
  {
    name: 'Senegal',
    continent: 'Africa',
    region: 'Western Africa',
    alpha3code: 'SEN',
    numberOfSpots: 28,
  },
  {
    name: 'Serbia',
    continent: 'Europe',
    region: 'Southern Europe',
    alpha3code: 'SRB',
    numberOfSpots: 2,
  },
  {
    name: 'Singapore',
    continent: 'Asia',
    region: 'Southeast Asia',
    alpha3code: 'SGP',
    numberOfSpots: 1,
  },
  {
    name: 'Slovakia',
    continent: 'Europe',
    region: 'Eastern Europe',
    alpha3code: 'SVK',
    numberOfSpots: 3,
  },
  {
    name: 'Slovenia',
    continent: 'Europe',
    region: 'Southern Europe',
    alpha3code: 'SVN',
    numberOfSpots: 3,
  },
  {
    name: 'Spain',
    continent: 'Europe',
    region: 'Southern Europe',
    alpha3code: 'ESP',
    numberOfSpots: 97,
  },
  {
    name: 'Sri Lanka',
    continent: 'Asia',
    region: 'Southern and Central Asia',
    alpha3code: 'LKA',
    numberOfSpots: 10,
  },
  {
    name: 'Switzerland',
    continent: 'Europe',
    region: 'Western Europe',
    alpha3code: 'CHE',
    numberOfSpots: 5,
  },
  {
    name: 'Tajikistan',
    continent: 'Asia',
    region: 'Southern and Central Asia',
    alpha3code: 'TJK',
    numberOfSpots: 10,
  },
  {
    name: 'Thailand',
    continent: 'Asia',
    region: 'Southeast Asia',
    alpha3code: 'THA',
    numberOfSpots: 11,
  },
  {
    name: 'Transnistria',
    continent: 'Europe',
    region: 'Eastern Europe',
    alpha3code: 'TRA',
    numberOfSpots: 2,
  },
  {
    name: 'Tunisia',
    continent: 'Africa',
    region: 'Northern Africa',
    alpha3code: 'TUN',
    numberOfSpots: 16,
  },
  {
    name: 'Turkey',
    continent: 'Asia',
    region: 'Middle East',
    alpha3code: 'TUR',
    numberOfSpots: 26,
  },
  {
    name: 'Ukraine',
    continent: 'Europe',
    region: 'Eastern Europe',
    alpha3code: 'UKR',
    numberOfSpots: 2,
  },
  {
    name: 'United Arab Emirates',
    continent: 'Asia',
    region: 'Middle East',
    alpha3code: 'ARE',
    numberOfSpots: 4,
  },
  {
    name: 'United Kingdom',
    continent: 'Europe',
    region: 'British Islands',
    alpha3code: 'GBR',
    numberOfSpots: 7,
  },
  {
    name: 'United States',
    continent: 'North America',
    region: 'North America',
    alpha3code: 'USA',
    numberOfSpots: 7,
  },
  {
    name: 'Uzbekistan',
    continent: 'Asia',
    region: 'Southern and Central Asia',
    alpha3code: 'UZB',
    numberOfSpots: 11,
  },
  {
    name: 'Vatican City State',
    continent: 'Europe',
    region: 'Southern Europe',
    alpha3code: 'VAT',
    numberOfSpots: 1,
  },
  {
    name: 'Vietnam',
    continent: 'Asia',
    region: 'Southeast Asia',
    alpha3code: 'VNM',
    numberOfSpots: 7,
  },
];
