export const countryStatsMock = {
  info: {
    id: 102,
    name: 'Iran',
    region: 'Southern and Central Asia',
    continent: 'Asia',
    alpha2code: 'IR',
    alpha3code: 'IRN',
    surfaceArea: 1648195,
    population: 67702000,
    lifeExpectancy: 70,
    independenceYear: 1906,
    governmentForm: 'Islamic Republic',
    localName: 'Iran',
    independent: true,
    fullyRecognized: true,
    visited: true,
    statistics: true,
    flagUrl: 'https://restcountries.eu/data/irn.svg',
    borders: '["AFG","ARM","AZE","IRQ","PAK","TUR","TKM"]',
  },
  citiesVisited: [
    'Abyaneh',
    'Bandar Abbas',
    'Ghalat',
    'Hanjan',
    'Hormuz',
    'Isfahan',
    'Kashan',
    'Maranjab',
    'Na\u0027in',
    'Natanz',
    'Persepolis',
    'Qom',
    'Shiraz',
    'Tehran',
    'Yazd',
  ],
  statesVisited: [],
  kilometersWalked: '211.23',
  nights: {
    count: { free: '25', paid: '1', total: 26 },
    spots: {
      Wildcamping: '9',
      Hospitality: '7',
      Review: '5',
      Couchsurfing: '4',
      Hostel: '1',
    },
    infoExtra: { Mosque: '2' },
  },
  hitchhikes: {
    totalKilometers: 2077,
    totalKilometersOpenAir: 45,
    daysOnTheRoad: '12',
    totalCars: 30,
    distances: { longest: '484.00', shortest: '1.00', average: '67.000000' },
    minutesWaiting: {
      total: '33.27',
      waits: { longest: '5.00', shortest: '0.00', average: '1.073226' },
      carsPerHour: [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        3,
        7,
        4,
        4,
        3,
        2,
        2,
        1,
        2,
        2,
        0,
        0,
        0,
        0,
      ],
      kilometersPerHour: [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        365,
        160,
        74,
        111,
        554,
        141,
        149,
        39,
        299,
        184,
        0,
        0,
        0,
        0,
      ],
      waitingPerHour: [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        5,
        2.59,
        10.5,
        10,
        2.34,
        0,
        2.17,
        0,
        0.67,
        0,
        0,
        0,
        0,
        0,
      ],
    },
  },
  expenses: {
    sum: '543.21',
    categories: {
      ACCOMMODATION: '100.00',
      DRINK: '50.00',
      FOOD: '100.00',
      'INTERNATIONAL TRANSPORT': '200.20',
      OTHERS: '0.50',
      PHONE: '4.44',
      SIGHTSEEING: '55.55',
      TRANSPORT: '22.22',
      VISA: '88.88',
    },
  },
};
