export const FETCH_COUNTRIES_BEEN = 'FETCH_COUNTRIES_BEEN';
export const FETCH_COUNTRIES_BEEN_START = 'FETCH_COUNTRIES_BEEN_START';
export const FETCH_COUNTRIES_BEEN_SUCCESS = 'FETCH_COUNTRIES_BEEN_SUCCESS';
export const FETCH_COUNTRIES_BEEN_FAIL = 'FETCH_COUNTRIES_BEEN_FAIL';

export const FETCH_STATS = 'FETCH_STATS';
export const FETCH_STATS_START = 'FETCH_STATS_START';
export const FETCH_STATS_SUCCESS = 'FETCH_STATS_SUCCESS';
export const FETCH_STATS_FAIL = 'FETCH_STATS_FAIL';

export const FETCH_TRIPS = 'FETCH_TRIPS';
export const FETCH_TRIPS_START = 'FETCH_TRIPS_START';
export const FETCH_TRIPS_SUCCESS = 'FETCH_TRIPS_SUCCESS';
export const FETCH_TRIPS_FAIL = 'FETCH_TRIPS_FAIL';

export const FETCH_JOURNALS = 'FETCH_JOURNALS';
export const FETCH_JOURNALS_START = 'FETCH_JOURNALS_START';
export const FETCH_JOURNALS_SUCCESS = 'FETCH_JOURNALS_SUCCESS';
export const FETCH_JOURNALS_FAIL = 'FETCH_JOURNALS_FAIL';

export const FETCH_COUNTRY_STATS = 'FETCH_COUNTRY_STATS';
export const FETCH_COUNTRY_STATS_START = 'FETCH_COUNTRY_STATS_START';
export const FETCH_COUNTRY_STATS_SUCCESS = 'FETCH_COUNTRY_STATS_SUCCESS';
export const FETCH_COUNTRY_STATS_FAIL = 'FETCH_COUNTRY_STATS_FAIL';

export const TOGGLE_GRADUAL_COLORING = 'TOGGLE_GRADUAL_COLORING';
export const SET_SELECTED_CONTINENT = 'SET_SELECTED_CONTINENT';
export const SET_SELECTED_REGION = 'SET_SELECTED_REGION';
