export const FETCH_STATS = 'FETCH_STATS';
export const FETCH_STATS_START = 'FETCH_STATS_START';
export const FETCH_STATS_SUCCESS = 'FETCH_STATS_SUCCESS';
export const FETCH_STATS_FAIL = 'FETCH_STATS_FAIL';
