export const FETCH_VISITED_COUNTRIES_START = 'FETCH_VISITED_COUNTRIES_START';
export const FETCH_VISITED_COUNTRIES_SUCCESS = 'FETCH_VISITED_COUNTRIES_SUCCESS';
export const FETCH_VISITED_COUNTRIES_FAIL = 'FETCH_VISITED_COUNTRIES_FAIL';

export const TOGGLE_GRADUAL_COLORING = 'TOGGLE_GRADUAL_COLORING';
export const SET_SELECTED_CONTINENT = 'SET_SELECTED_CONTINENT';
export const SET_SELECTED_REGION = 'SET_SELECTED_REGION';
