export const FETCH_COUNTRIES_BEEN = 'FETCH_COUNTRIES_BEEN';
export const FETCH_COUNTRIES_BEEN_START = 'FETCH_COUNTRIES_BEEN_START';
export const FETCH_COUNTRIES_BEEN_SUCCESS = 'FETCH_COUNTRIES_BEEN_SUCCESS';
export const FETCH_COUNTRIES_BEEN_FAIL = 'FETCH_COUNTRIES_BEEN_FAIL';

export const FETCH_COUNTRY_STATS = 'FETCH_COUNTRY_STATS';
export const FETCH_COUNTRY_STATS_START = 'FETCH_COUNTRY_STATS_START';
export const FETCH_COUNTRY_STATS_SUCCESS = 'FETCH_COUNTRY_STATS_SUCCESS';
export const FETCH_COUNTRY_STATS_FAIL = 'FETCH_COUNTRY_STATS_FAIL';

export const TOGGLE_GRADUAL_COLORING = 'TOGGLE_GRADUAL_COLORING';
export const SET_SELECTED_CONTINENT = 'SET_SELECTED_CONTINENT';
export const SET_SELECTED_REGION = 'SET_SELECTED_REGION';
