export const FETCH_VISITED_COUNTRIES = 'FETCH_VISITED_COUNTRIES';
export const FETCH_VISITED_COUNTRIES_START = 'FETCH_VISITED_COUNTRIES_START';
export const FETCH_VISITED_COUNTRIES_SUCCESS = 'FETCH_VISITED_COUNTRIES_SUCCESS';
export const FETCH_VISITED_COUNTRIES_FAIL = 'FETCH_VISITED_COUNTRIES_FAIL';

export const FETCH_COUNTRY_STATS = 'FETCH_COUNTRY_STATS';
export const FETCH_COUNTRY_STATS_START = 'FETCH_COUNTRY_STATS_START';
export const FETCH_COUNTRY_STATS_SUCCESS = 'FETCH_COUNTRY_STATS_SUCCESS';
export const FETCH_COUNTRY_STATS_FAIL = 'FETCH_COUNTRY_STATS_FAIL';

export const TOGGLE_GRADUAL_COLORING = 'TOGGLE_GRADUAL_COLORING';
export const SET_SELECTED_CONTINENT = 'SET_SELECTED_CONTINENT';
export const SET_SELECTED_REGION = 'SET_SELECTED_REGION';
